version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network
  production_agent:
    build:
      context: .
      dockerfile: Dockerfile.production_agent
    depends_on:
      - rabbitmq
    networks:
      - app_network
    environment:
      - RABBITMQ_HOST=${rabbitmq_host}
      - PROMETHEUS_PORT=${prometheus_port}
    deploy:
      resources:
        limits:
          cpus: "${max_cpu}"
          memory: "${max_memory}"
    command: python production_agent.py

  inventory_agent:
    build:
      context: .
      dockerfile: Dockerfile.inventory_agent
    depends_on:
      - rabbitmq
    networks:
      - app_network
    environment:
      - RABBITMQ_HOST=${rabbitmq_host}
      - PROMETHEUS_PORT=${prometheus_port}
    deploy:
       resources:
        limits:
          cpus: "${max_cpu}"
          memory: "${max_memory}"
    command: python inventory_agent.py

  dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - app_network
    environment:
      - RABBITMQ_HOST=${rabbitmq_host}
    deploy:
      resources:
        limits:
          cpus: "${max_cpu}"
          memory: "${max_memory}"

  odoo:
      image: odoo:14
      depends_on:
          - db
      ports:
          - "8069:8069"
      networks:
         - app_network
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    networks:
      - app_network
  data_processing:
    build:
      context: .
      dockerfile: Dockerfile.data_processing
    depends_on:
      - rabbitmq
    networks:
      - app_network
    environment:
      - RABBITMQ_HOST=${rabbitmq_host}
      - PROMETHEUS_PORT=${prometheus_port}
    deploy:
       resources:
          limits:
            cpus: "${max_cpu}"
            memory: "${max_memory}"
    command: python data_processing.py

  iot_server:
    build:
      context: server_iot
      dockerfile: Dockerfile
    ports:
        - "8069:8069"
    networks:
      - app_network
    environment:
      - API_KEY=${iot_api_key}
    deploy:
       resources:
          limits:
           cpus: "${max_cpu}"
           memory: "${max_memory}"
networks:
  app_network:
    driver: bridge